name: Fetch centredesarts-ca (centre-des-arts-juliette-lassonde)
# also crawled by footlight-console

on:
  workflow_dispatch:
  schedule:
    - cron: '30 7 * * 2'
     
jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v4
        with:
          mode: "fetch-push"
          page-url: "https://www.centredesarts.ca/programmation/"
          entity-identifier: "div.portfolio-text-title a"
          artifact: "centredesarts-ca"
          publisher: "${{ vars.CAPACOA_BOT }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
          cloudflare-private-key: ${{ secrets.CLOUDFLARE_PRIVATE_KEY }}
