name: Fetch odyscene-com Events

on:
  workflow_dispatch:
    
jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v3
        with:
          mode: "fetch-push"
          artifact: "odyscene-com"
          publisher: "https://github.com/saumier#this"
          page-url: "https://odyscene.com/event-sitemap.xml,https://odyscene.com/event-sitemap2.xml"
          entity-identifier: "loc"
          token: "${{ secrets.GITHUB_TOKEN }}"
