# This workflow can be used to crawl any website by passing minimal parameters
# This workflow is also called by Nebula when using the form to create a new artifact with the pipeline "Orion JSON-LD Website"
# It does not have a schedule. Create a custom workflow to add a schedule.

name: Orion Fetch and Push

on:
  workflow_dispatch:
   inputs:
      page-url:
        description: 'URL of the page to crawl'
      entity-identifier:
        description: 'Identifier of the entity'
      artifact:
        description: 'name of artifact'
      publisher:
        description: 'publisher id'
        
      
jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v3
        with:
          mode: "fetch-push"
          artifact: "${{ inputs.artifact }}"
          publisher: "${{ inputs.publisher }}"
          page-url: "${{ inputs.page-url }}"
          entity-identifier: "${{ inputs.entity-identifier }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
          cloudflare-private-key: ${{ secrets.CLOUDFLARE_PRIVATE_KEY }}
