name: Fetch rosslandartscouncil-com

on:
  workflow_dispatch:
    schedule:
    - cron: '28 16 * * 3'

jobs:
  artsdata-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v3
        with:
          mode: "fetch-push"
          artifact: "rosslandartscouncil-com"
          publisher: "https://github.com/fjjulien#this"
          page-url: "https://rosslandartscouncil.com/events/"
          entity-identifier: "//a[@class='tribe-events-calendar-list__event-title-link tribe-common-anchor-thin']"
          token: ${{ secrets.GITHUB_TOKEN }}
