# Delete wokflow because this graph is already loaded into Artsdata using the pipeline action.

name: Fetch spec-qc-ca-events Events

on:
  workflow_dispatch:
#  schedule:
#    - cron: '30 2 * * 6'
    
jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v3
        with:
          mode: "fetch-push"
          artifact: "spec-qc-ca-events"
          publisher: "${{ vars.CAPACOA_BOT }}"
          page-url: "https://spec.qc.ca/programmation"
          token: "${{ secrets.GITHUB_TOKEN }}"
          cloudflare-private-key: ${{ secrets.CLOUDFLARE_PRIVATE_KEY }}
