name: Fetch thecultch-com Events
# See source log: https://github.com/artsdata-stewards/source-logs/issues/1

on:
  workflow_dispatch:
  schedule:
    - cron: '15 21 * * 3'
    
jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v4
        with:
          mode: "fetch-push"
          artifact: "thecultch-com"
          publisher: "${{ vars.CAPACOA_BOT }}"
          page-url: "https://thecultch.com/event-sitemap.xml"
          entity-identifier: "loc"
          token: "${{ secrets.GITHUB_TOKEN }}"
          cloudflare-private-key: ${{ secrets.CLOUDFLARE_PRIVATE_KEY }}
