name: Fetch yardbirdsuite-com Events

on:
  workflow_dispatch:
  schedule:
    - cron: '57 2 * * 3'
    
jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v3
        with:
          mode: "fetch-push"
          artifact: "yardbirdsuite-com"
          publisher: "${{ vars.CAPACOA_BOT }}"
          page-url: "https://yardbirdsuite.com/events/"
          token: "${{ secrets.GITHUB_TOKEN }}"
          cloudflare-private-key: ${{ secrets.CLOUDFLARE_PRIVATE_KEY }}
